### ISSUE TITLE
Positioning of input-method popups based on `set_point` doesn't seem to be correct

### ISSUE THREAD

**Issue by ids1024** [Smithay/smithay#1045]
In Anvil, with multiple monitors, the IME popup seems to be appearing simultaneously at the same position on multiple displays? It should only appear on the monitor with the relevant surface.

The way `set_point` is called in anvil doesn't seem quite correct in general. It's called in a few places. In one place it's based on the return value of `window.surface_under` and in another on the return value of `space.element_under`. But looking at the docs for those function, it looks like the first returns coordinates relative to the window, and the second relative to the space? And we're not storing what space the surface should be on here (though anvil only uses one).

(Perhaps part of the issue there is that `Point<i32, Logical>` coordinates are being used for coordinates relative to different things?)

Probably it would be better to store the surface, and make sure it is positioned relative to that? But in particular this should match the surface with text-input focus. So with https://github.com/Smithay/smithay/pull/1044 we should be able to avoid any explicit code setting this in anvil or other compositors.

**Comment by rano-oss** [comment]
hmm, I agree, I just set it in anvil everywhere I thought it was needed. The correct behavior is that `set point` should set the top left corner position relative to the space (I understand "space" as my screen here) of the currently focused window/surface/other. The focused windows sends an event with the relative position inside of the surface, so that is handled. 

Ideally this would happen without any compositor involvement, any input on how to achieve that will be greatly appreciated.

**Comment by ids1024** [comment]
> I understand "space" as my screen here

"space" in smithay is more like a "workspace" and may span multiple physical monitors.

> Ideally this would happen without any compositor involvement(I mean that as it should be handled in smithay, not in the compositor implementation)

Yep. Trying to figure out how best to do that. It doesn't naturally fit with how popup surfaces work for a couple reasons...

**Comment by ids1024** [comment]
Suppose for instance that libc spawned Perl to deal with strings because C is too hard. But no serious OS would do that. :laughing:
https://news.ycombinator.com/item?id=18920122

(The original tweet won't load without being logged in, apparently, because of course Twitter changed that today.)

**Comment by rano-oss** [comment]
Reminds me of when I tried to apply to CodeWeavers(the wine people), thinking my micro-controller C experience would be enough. The code test they gave me was all centered around handling strings with C. I understand why one would want to do it in any other language than C.

relibc cannot reach feature parity fast enough 😆
------- Original Message -------

**Comment by kchibisov** [comment]
@ids1024 is this still an issue?

**Comment by ids1024** [comment]
Yeah, it's fair to close this now. IME popups are now handled with `PopupManager`, and `set_point` no longer exists. So if there are any issues now, they're different ones.
