### ISSUE TITLE
Consider releasing a new version

### ISSUE THREAD

**Issue by saihaze** [Smithay/smithay#1051]
Now the last version was released in 2021, which is rather old. To reach a newer version, we have to depend on git.

**Comment by orowith2os** [comment]
The name could be a reference to the game of "hot and cold" where the name is "Getting warmer" :)

Also, I imagine the developers have a few blocking issues they'd like to sort out before a new release. Documentation especially.

**Comment by Drakulix** [comment]
For what it's worth, we actually have a milestone for the next release and the amount of open issues for it has been going down significantly recently: https://github.com/Smithay/smithay/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v0.4%3A+Gathering+raw+ores%22

**Comment by jzbor** [comment]
Hi, is there any timetable or estimate on when the release of  a new version is planned?

**Comment by orowith2os** [comment]
There are two more items on the linked milestone. Guess from that.

**Comment by saihaze** [comment]
I totally forgot about this issue 😅
I will close it
