### ISSUE TITLE
dma-buf and dumb buffers doc link broken

### ISSUE THREAD

**Issue by aurabindo** [Smithay/smithay#1079]
The 01.org links appear to be broken in dmabuf.rs and dumb.rs:

https://01.org/linuxgraphics/gfx-docs/drm/driver-api/dma-buf.html
https://01.org/linuxgraphics/gfx-docs/drm/gpu/drm-kms.html#dumb-buffer-objects

**Comment by Drakulix** [comment]
Thanks for pointing this out. Should be updated.
