### ISSUE TITLE
Updates to calloop / wayland-rs before releasing 0.4

### ISSUE THREAD

**Issue by elinorbgr** [Smithay/smithay#1105]
So, there is quite a bit of breaking changes going on with wayland-rs and calloop, which will prompt in the near future new releases.

I suggest once these releases are done, we update Smithay to those new version (it should be quite easy to do), and then release the 0.4.

Thoughts?

Notable changes I'm thinking about:

- https://github.com/Smithay/wayland-rs/pull/650
- https://github.com/Smithay/calloop/pull/144

**Comment by ids1024** [comment]
https://github.com/Smithay/smithay/pull/1041 already has changes for the new calloop version.
