### ISSUE TITLE
SeatHandler::cursor_image doesn't get called often enough on XWayland surfaces

### ISSUE THREAD

**Issue by luveti** [Smithay/smithay#1113]
My compositor only makes use of XWayland (for now) so my SeatHandler impl looks like this:
```rs
impl SeatHandler for Compositor {
    type KeyboardFocus = X11Surface;
    type PointerFocus = X11Surface;
    // ...
}
```

When adding cursor support, I took inspiration from Anvil when implementing it. But noticed `SeatHandler::cursor_image` only gets called when running `xrdb ~/.Xresources`. So I've added code to listen for `CursorNotify` events in my related pull request.

Is anyone else having this issue? It would probably be better to figure out why the existing cursor code isn't working, or hook up the `CursorNotify` event to the existing `SeatHandler::cursor_image` code, but I didn't have time to dig through the internals.

**Comment by Drakulix** [comment]
`cursor_image` only is called when a new surface is attached. Xwayland re-uses the same surface, so an update isn't necessarily. What issue are you specifically encountering?

**Comment by luveti** [comment]
Ahh that would explain it then! Looking into it further it appears that I was not calling the `frame_callbacks` on that surface.

Anvil is quite the complex beast and I was bound to miss a few things while distilling it into my own compositor. I had previously missed calling `X11Wm::commit_hook` in `CompositorHandler::commit`, which was not fun to debug!

Thanks for the great work and quick reply!

**Comment by Drakulix** [comment]
Ah yes, I have too hit my head against that wall, when implementing the xwayland integration. Anvil previously completely missed sending frame events to cursor surfaces and since most wayland clients don't animate cursor this was never a problem... until I encountered Xwayland is re-using the surface. :sweat_smile:
