### ISSUE TITLE
Evaluate use of newer MSRV

### ISSUE THREAD

**Issue by cmeissl** [Smithay/smithay#1241]
I think if we're willing to uprev the rust dependency to 1.70.0, OnceCell should contain all the functionality you need.

_Originally posted by @bwidawsk in https://github.com/Smithay/smithay/pull/1228#discussion_r1408232920_

**Comment by ids1024** [comment]
The `once_cell` crate is an option without bumping MSRV. So this doesn't seem like an especially strong reason to need an MSRV bump. (But in general, I don't see an issue with requiring 1.70.0).

**Comment by PolyMeilex** [comment]
It got bumped to 1.72 in #1332
