### ISSUE TITLE
elogind support

### ISSUE THREAD

**Issue by vberger** [Smithay/smithay#127]
As an alternative to systemd-logind, we need to support [elogind](https://github.com/elogind/elogind). It uses the exact same dbus API as logind, so it is just a matter of abstracting this part of the code over the 2 different system libs:

https://github.com/Smithay/smithay/blob/48264926e65d8eb4c05352ca38fb3fef5ce38f87/src/backend/session/dbus/logind.rs#L90-L93

**Comment by skyne98** [comment]
What about the systems that do not use d-bus? Maybe there should be an option to use the elogind's filesystem-based interface or even statically link the libelogind?

**Comment by vberger** [comment]
I didn't even know that elogind had such an interface tbh. These would definitely be on scope, as long as someone with the necessary knowledge is willing to implement & maintain them.

**Comment by kchibisov** [comment]
Upstream PR https://github.com/jmesmon/rust-systemd/pull/97
