### ISSUE TITLE
Monitors not lighting up DRM problems

### ISSUE THREAD

**Issue by YaLTeR** [Smithay/smithay#1289]
cc @cmeissl 

I'm on a laptop with iGPU + dGPU, however for this test everything is connected to and rendered on the dGPU. Sometimes when switching TTY to my compositor, some monitors (usually external, but I saw the internal one too) fail to light up, or fail to start working. Switching TTY to a vconsole or to GDM always works even in those cases.

### Case 1

Compositor disconnects and then reconnects connectors upon TTY switch. Code: https://github.com/YaLTeR/niri/blob/e4643c6dbea64304c9e8b074699227e8654c989d/src/backend/tty.rs#L323-L345

Switching TTY fails to light up the monitor. Compositor log:
1. Disconnect succeeds.
2. Connect fails, probably at the `drm.create_surface()` call.

Replugging the monitor lights it up as normal.

DRM debug: [drm_debug-fail_to_turn_on-reconnect.log](https://github.com/Smithay/smithay/files/13946443/drm_debug-fail_to_turn_on-reconnect.log)

Points of interest:
```
[37255.783697] [drm:dm_crtc_helper_atomic_check [amdgpu]] Can't enable a CRTC without enabling the primary plane
[37255.784001] amdgpu 0000:03:00.0: [drm:drm_atomic_helper_check_planes] [CRTC:95:crtc-1] atomic driver check failed
[37255.784005] [drm:amdgpu_dm_atomic_check [amdgpu]] drm_atomic_helper_check_planes() failed
[37255.784289] [drm:amdgpu_dm_atomic_check [amdgpu]] Atomic check failed with err: -22
```
```
[37255.784703] amdgpu 0000:03:00.0: [drm:drm_atomic_helper_check_modeset] [CRTC:91:crtc-0] enabled/connectors mismatch
[37255.784706] [drm:amdgpu_dm_atomic_check [amdgpu]] drm_atomic_helper_check_modeset() failed
[37255.784987] [drm:amdgpu_dm_atomic_check [amdgpu]] Atomic check failed with err: -22
[37255.785268] amdgpu 0000:03:00.0: [drm:drm_atomic_check_only] atomic driver check for 00000000c31d0d76 failed: -22
```
```
[37255.829572] amdgpu 0000:03:00.0: [drm:drm_atomic_helper_check_modeset] [CRTC:91:crtc-0] mode changed
[37255.829577] amdgpu 0000:03:00.0: [drm:drm_atomic_helper_check_modeset] [CRTC:95:crtc-1] enabled/connectors mismatch
[37255.829468] [drm:gfx_v10_0_eop_irq [amdgpu]] IH: CP EOP
[37255.829581] [drm:amdgpu_dm_atomic_check [amdgpu]] drm_atomic_helper_check_modeset() failed
[37255.829935] [drm:amdgpu_ih_process [amdgpu]] amdgpu_ih_process: rptr 254016, wptr 254048
[37255.830079] [drm:amdgpu_dm_atomic_check [amdgpu]] Atomic check failed with err: -22
[37255.830621] amdgpu 0000:03:00.0: [drm:drm_atomic_check_only] atomic driver check for 00000000dd04f02a failed: -22
```
```
[37255.834543] amdgpu 0000:03:00.0: [drm:drm_atomic_helper_check_modeset] [CRTC:91:crtc-0] mode changed
[37255.834547] amdgpu 0000:03:00.0: [drm:drm_atomic_helper_check_modeset] [CRTC:95:crtc-1] enabled/connectors mismatch
[37255.834550] [drm:amdgpu_dm_atomic_check [amdgpu]] drm_atomic_helper_check_modeset() failed
[37255.834783] [drm:amdgpu_ih_process [amdgpu]] amdgpu_ih_process: rptr 254176, wptr 254208
[37255.835026] [drm:amdgpu_dm_atomic_check [amdgpu]] Atomic check failed with err: -22
[37255.835240] [drm:gfx_v10_0_eop_irq [amdgpu]] IH: CP EOP
[37255.835569] amdgpu 0000:03:00.0: [drm:drm_atomic_check_only] atomic driver check for 00000000dd04f02a failed: -22
```

### Case 2

Compositor calls device changed code upon TTY switch. Code: https://github.com/YaLTeR/niri/blob/e4643c6dbea64304c9e8b074699227e8654c989d/src/backend/tty.rs#L347-L360

Currently what I'm seeing is that it fails with two external monitors connected, but succeeds with just one. Replugging the monitor sometimes lights up both monitors, sometimes lights up just one (interestingly enough, not the one that is replugged), then upon second replug lights up the second one too.

Compositor log:
```
янв 16 10:50:53 niri[155321]: 2024-01-16T06:50:53.341558Z DEBUG niri::backend::tty: resuming session
янв 16 10:50:53 niri[155321]: 2024-01-16T06:50:53.603043Z DEBUG niri::backend::tty: device changed: 57856
янв 16 10:50:53 niri[155321]: 2024-01-16T06:50:53.603137Z DEBUG niri::backend::tty: device changed: 57857
янв 16 10:50:53 niri[155321]: 2024-01-16T06:50:53.619300Z ERROR niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: Atomic Test failed for new properties on crtc (crtc::Handle(95))
янв 16 10:50:53 niri[155321]: 2024-01-16T06:50:53.619948Z ERROR niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: Atomic Test failed for new properties on crtc (crtc::Handle(99))
янв 16 10:50:53 niri[155321]: 2024-01-16T06:50:53.634316Z ERROR niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: Atomic Test failed for new properties on crtc (crtc::Handle(95))
янв 16 10:50:55 niri[155321]: 2024-01-16T06:50:55.918110Z ERROR niri::backend::tty: error queueing frame: The underlying drm surface encountered an error: Atomic Test failed for new properties on crtc (crtc::Handle(95))
```
That is, all that code succeeds, then every time we try to draw the monitor, it fails.

DRM debug:  [drm_debug-fail_to_turn_on-change-two_external_monitors.log](https://github.com/Smithay/smithay/files/13946460/drm_debug-fail_to_turn_on-change-two_external_monitors.log)

## DRM Info

- [drm_info-two_external_monitors-working.log](https://github.com/Smithay/smithay/files/13946470/drm_info-two_external_monitors-working.log)
- [drm_info-two_external_monitors-broken.log](https://github.com/Smithay/smithay/files/13946472/drm_info-two_external_monitors-broken.log): DRM info during the broken state, before replugging
- [drm_info-one_external_monitor-working.log](https://github.com/Smithay/smithay/files/13946473/drm_info-one_external_monitor-working.log): DRM info when it works, after replugging

**Comment by ids1024** [comment]
I discovered an issue I've seen with this for Nvidia outputs on a dual GPU laptop is due to the VRAM being full. Still not sure what's causing that: https://github.com/pop-os/cosmic-comp/issues/243

Though it's probably unrelated to the issue you're seeing with AMD.

**Comment by cmeissl** [comment]
I can some sort of reproduce this in anvil (and niri) and identified multiple issues.  Some of them are non
critical, like resetting planes, but need to be fixed anyway.

But the by far worst issue I was able to reproduce is `Case 2`, in which case anvil will also panic.
After a bit of back and forth this seems to only happen with multiple monitor connected like reported.
Which kind of makes sense, because this seems to only fail when we try to switch connectors, which can/should
only happen with multiple outputs.

So, what happens is that by calling [reset_state](https://github.com/Smithay/smithay/blob/2b4d49dc26ceddc33db7fef6c5f249394a5557f1/src/backend/drm/surface/atomic.rs#L1056) after a session resume
we will read out the current connectors. When calling `queue_frame` we will end in [commit](https://github.com/Smithay/smithay/blob/2b4d49dc26ceddc33db7fef6c5f249394a5557f1/src/backend/drm/surface/atomic.rs#L548) which detects some change in the connectors and then tries to disable the current connector and enable the pending connector.
And this is what will fail and print out `Atomic Test failed for new properties on crtc`.

**Comment by cmeissl** [comment]
The provided drm log also points in the same direction, something is going horrible wrong with the connectors

> [88233.574515] amdgpu 0000:03:00.0: [drm:drm_atomic_check_only] checking 000000009b718254
>[88233.574519] amdgpu 0000:03:00.0: [drm:drm_atomic_helper_check_modeset] [CRTC:95:crtc-1] mode changed
> [88233.574524] amdgpu 0000:03:00.0: [drm:drm_atomic_helper_check_modeset] [CRTC:99:crtc-2] enabled/connectors mismatch

**Comment by cmeissl** [comment]
The same happens on my intel only laptop, when anvil selects a different crtc then currently active on the tty the next switch back from a different tty will fail. So it seems we have two issues here, or at least one issue and a question.

- Why does it succeed to do the initial crct switch, but fail after a tty switch
- Why is the used crtc non deterministic (or why does it sometimes differ from the crct the tty uses)

**Comment by cmeissl** [comment]
Okay, I believe to have found the reason why this fails...
We try to update the outputs one by one, this won't work because we can not activate a CRTC while it is still bound to a different connector.

**Comment by cmeissl** [comment]
> The same happens on my intel only laptop, when anvil selects a different crtc then currently active on the tty the next switch back from a different tty will fail. So it seems we have two issues here, or at least one issue and a question.
> 
>     * Why does it succeed to do the initial crct switch, but fail after a tty switch
> 
>     * Why is the used crtc non deterministic (or why does it sometimes differ from the crct the tty uses)

The reason why it initially succeeds is the same why #1295 should solve it, we reset all CRTCs

**Comment by cmeissl** [comment]
Might also explain why turning off and on can help. This should reset the state for one connector, potentially allowing the other to proceed. Might get a bit more tricky with more than two connected connectors.
