### ISSUE TITLE
cargo build fails on fedora 29

### ISSUE THREAD

**Issue by rokit** [Smithay/smithay#135]
I'm getting: `error: failed to run custom build command for libudev-sys v0.1.4`
I googled it and one solution was to install `pkg-config`. Unfortunately, I already had it installed. Any ideas?

**Comment by Drakulix** [comment]
Have you installed `systemd-devel`? You need the development files of libudev and those come bundled with systemd on fedora.

**Comment by rokit** [comment]
That was it! Thanks.

**Comment by rokit** [comment]
Now when I try `cargo run -p anvil -- --winit` I get `error: linking with cc failed: exit code: 1`. Any ideas for that one?

**Comment by rokit** [comment]
Ok I needed `libxkbcommon-devel`. I also need linput, but not finding that with `dnf search`.

**Comment by rokit** [comment]
Ok, also needed `libinput-devel` and `mesa-libgbm-devel`.

**Comment by JoshMcguigan** [comment]
I can confirm that `libxkbcommon-devel`, `libinput-devel`, and `mesa-libgbm-devel` are still the necessary dependencies on fedora 32.

**Comment by vberger** [comment]
Probably worth adding these in the readme I guess.
