### ISSUE TITLE
Possibly wrong window geometry size with wp-viewporter

### ISSUE THREAD

**Issue by YaLTeR** [Smithay/smithay#1357]
I tried adding wp-viewporter to niri and found ~~two~~ one issue so far.

If you run `weston-scaler`, then its `window.geometry().size` will not match its destination rectangle. You can tell by the border + background size around the window.

![Screenshot from 2024-03-10 18-04-35](https://github.com/Smithay/smithay/assets/1794388/1e4ecdfe-e087-43ab-8294-611576a4a6d5)

I'm not sure how to tell what Weston and sway do exactly, but `weston-scaler -h` says "window size 220x308 px" which to me implies `window.geometry().size`.

![image](https://github.com/Smithay/smithay/assets/1794388/e1f03175-57a1-4fd1-be87-274065be37a0)

The Anvil "window preview" seems to work fine and that uses `window.bbox()` rather than geometry from what I can tell?

The second issue was originally that Chromium fails to accept pointer input beyond its initial configure window size if resized bigger than that, but it seems that giving it a (0, 0) initial configure makes that go away. Non-zero initial configure claims another victim it seems... Although, I'll have to test this more; I think I saw the bug trigger even with a (0, 0) initial configure once.

It appears that without viewporter, or with viewporter and initial configure = 0, Chromium/Electron sets a NULL input region, but with viewporter and nonzero initial configure, it sets a specific input region, and then never updates it?

**Comment by Drakulix** [comment]
So we possibly need to take the viewporter scale into account when returning the geometry?

**Comment by cmeissl** [comment]
> The Anvil "window preview" seems to work fine and that uses window.bbox() rather than geometry from what I can tell?

Yes, this is intended. I used the bbox here to include all subsurfaces in the preview.

**Comment by cmeissl** [comment]
Okay, imo there is no issue in the wp_viewporter implementation. 

But what is relevant from the spec is:

> When applied, the effective window geometry will be the set window geometry clamped to the bounding rectangle of the combined geometry of the surface of the xdg_surface and the associated subsurfaces.

I am pretty sure I implemented this somewhere in smithay, maybe it got lost during a refactor or is in some other abstraction.
