### ISSUE TITLE
Pasting images from wayland -> x11 truncates/corrupts the image

### ISSUE THREAD

**Issue by Ottatop** [Smithay/smithay#1380]
Reproducible in Anvil, cosmic-comp, and Pinnacle across my desktop and laptop (though they all use the same code for Wayland -> x11 selections so I guess that's expected).

Pasting to other Wayland clients works fine, but pasting the exact same image contents into an xwayland client results in a truncated or corrupted image, on my machines at least. The image gets pasted at the right dimensions, but they seem to be corrupted, filled with fully transparent/NUL bytes after the first few rows of pixels, truncated, or some combination of those.

The following is a PNG screenshot of a screencopy that was pasted into Discord running under X11 as it appears in element-desktop. It's filled with what seems to be transparency. Pasting into GIMP will fill the same parts with hex #979899, but I think that's a GIMP thing.

![image](https://github.com/Smithay/smithay/assets/120758733/b1faa156-b18c-444b-afce-4269c7f59abf)

Another user has the same problem as reported in pinnacle-comp/pinnacle#192, also PNGs.

They also gave me a screencopy that appears to have a chunk of corrupted bytes after the normal looking chunk, but I haven't been able to reproduce that:

<details>

<summary><b>Corrupted screencopy</b></summary>

![image](https://github.com/Smithay/smithay/assets/120758733/ac785bba-73bc-4a45-883a-0baf25bedeeb)

</details>

Any copied image has the same problem, not just screencopies, like ones copied off of Google images.

## JPEGs

Forcing the image to paste as a JPEG using `wl-paste --type image/jpeg | wl-copy` results in weird tiling artifacts:

<details>

<summary><b>Original cat JPEG</b></summary>

![image](https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg)

</details>

<details>

<summary><b>Messed up cat JPEG pasted into X11 GIMP (this is a screenshot)</b></summary>

![image](https://github.com/Smithay/smithay/assets/120758733/cd119c91-2b7e-417f-8f92-e9e7948b05ea)

</details>

**Comment by Drakulix** [comment]
Sounds like our wayland->x11 logic doesn't handle incremental selections correctly.

I don't really have the time to debug this atm, but essentially for large payloads, X11 splits the payload up into multiple incremental transfers. From what you are describing it looks like only the first couple of transfers (possibly only the very first) succeed.

The xwm-code responsible for this contains quite a few debug and trace statements, could you perhaps increase the log level and capture logs for this case?

Any patches or debugging attempts are of course also very welcome. Happy to help with guidance.

Also cool project! If you didn't already, I recommend joining our smithay matrix-space (see README). :)
