### ISSUE TITLE
Build error on s390x: src/wayland/shm/pool.rs:311:15  ..mem::zeroed() field `__glibc_reserved0` is private

### ISSUE THREAD

**Issue by ryanabx** [Smithay/smithay#1412]
Context: I'm working on releasing cosmic-comp in Fedora Rawhide (https://src.fedoraproject.org/rpms/cosmic-comp)

The build currently fails on 2 arches: i686 and s390x

i686 doesn't matter, I can choose not to build for that arch, s390x is required though, unfortunately.
https://koji.fedoraproject.org/koji/taskinfo?taskID=117083063

Looks like there's a member in smithay that's private on s390x:

![screenshot-2024-05-01-18-31-10](https://github.com/Smithay/smithay/assets/56272643/b12cd248-0d4c-4f23-abf8-c7224d396810)

**Comment by decathorpe** [comment]
The struct with private fields is not from smithay, but from the `libc` crate:
https://docs.rs/libc/latest/s390x-unknown-linux-gnu/libc/struct.sigaction.html

The `sigaction` struct has no private fields on most architectures, but not all. This results in most initialization methods not being fully portable.

I had a similar issue when packaging sudo-rs for Fedora Linux. The upstream solution to make `sigaction` struct initializing portable and arch-independent was implemented here:

https://github.com/memorysafety/sudo-rs/pull/830

**Comment by PolyMeilex** [comment]
Thank you both! Should be good now.
