### ISSUE TITLE
app_id for nested compositors

### ISSUE THREAD

**Issue by andrewbaxter** [Smithay/smithay#1418]
Right now AFAICT the `app_id` for smithay compositors nested under other wayland compositors is unset.  Forgive me if I'm totally wrong, I've been digging around a lot and might have missed something -- but afaict in `smithay::backend::winit::init` it uses `WindowBuilder()` but doesn't set platform-specific "name".  In the new winit `0.30` it appears to be configurable here: https://docs.rs/winit/0.30.0/winit/platform/wayland/trait.WindowAttributesExtWayland.html#tymethod.with_name 

I looked at wlroots too and it looks like wlroots hardcodes the app id "wlroots".  As a user I'd like to run nested compositors with different window decorations, etc. and having different app_ids would make this much easier (although, this requires the implementer to also expose an option to set the app id).

**Comment by Drakulix** [comment]
I don't see a reason, why we shouldn't make this configurable. Feel free to add the necessary methods to the winit backend to allow overriding this.

**Comment by andrewbaxter** [comment]
Oh awesome! I'll work on it when I next have a moment, it might not be right away though.

**Comment by Ottatop** [comment]
It's already configurable with a custom `WindowBuilder` through `backend::winit::init_from_builder`, isn't it?

**Comment by andrewbaxter** [comment]
Oh, you're right! Sorry, on `winit` < 0.30 it looks like it was `class_name` and wasn't platform-specific, it got renamed to `name` in 0.30 along with the removal of `WindowBuilder`.
