### ISSUE TITLE
Can't click in chromium tab after selecting and dragging text

### ISSUE THREAD

**Issue by phisch** [Smithay/smithay#1474]
I've confirmed with the folks over on the niri matrix that this issue happens in both niri, and cosmic-comp, so it's likely smithay related.

Whenever you select text in chromium, and drag it around (even just for 1 pixel), you now lose the ability to click in that tab, and have to close it.

Does not happen in non smithay based compositors. 

I hope the description is enough!

**Comment by cmeissl** [comment]
Thanks for reporting this issue! I was able to reproduce it and can see that we send an event which seems to be not sent by other compositors. Omitting this event seems to fix the issue.

**Comment by cmeissl** [comment]
Okay, so we are sending out `wl_data_source:event:dnd_drop_performed` followed by `wl_data_source::cancelled` which according to the spec should be fine.

> This event does not indicate acceptance, wl_data_source.cancelled may still be emitted afterwards if the drop destination does not accept any mime type.

At the same time it also defines

> However, this event might however not be received if the compositor cancelled the drag-and-drop operation before this event could happen.

Seems that wlroots (and probably also mutter, did not look at the source, only at the event stream) does only send the event in case the DnD action was accepted. Given this only seems to happen on chromium I tend to say this is a client bug which is not triggered by other compositors.
