### ISSUE TITLE
impl Hash for X11Surface?

### ISSUE THREAD

**Issue by m4rch3n1ng** [Smithay/smithay#1486]
i don't know enough about x11 and xwayland to know if there is anything that can be hashed, but would it be possible to `impl Hash for X11Surface`?

in the [current `PartialEq` impl](https://github.com/Smithay/smithay/blob/5854e0382a86c9fcae236928b93200b76df30928/src/xwayland/xwm/surface.rs#L95-L102) it compares `X11Surface::xwm` and `X11Surface::window`, which both seem to unique and immutable (?), but it also compares if the alive-ness of each surface, which wouldn't work if you also want to impl `Hash`

it's not a dealbreaker to me (using a `Vec` might even be faster than a `HashSet` for what i'm currently doing), i was just curious why it isn't implemented.

**Comment by Drakulix** [comment]
> i don't know enough about x11 and xwayland to know if there is anything that can be hashed, but would it be possible to `impl Hash for X11Surface`?
> 
> in the [current `PartialEq` impl](https://github.com/Smithay/smithay/blob/5854e0382a86c9fcae236928b93200b76df30928/src/xwayland/xwm/surface.rs#L95-L102) it compares `X11Surface::xwm` and `X11Surface::window`, which both seem to unique and immutable (?), but it also compares if the alive-ness of each surface, which wouldn't work if you also want to impl `Hash`
> 
> it's not a dealbreaker to me (using a `Vec` might even be faster than a `HashSet` for what i'm currently doing), i was just curious why it isn't implemented.

Aliveness is critical, as window id's might be re-used by Xwayland. (They are only unique for one moment in time and compositor might hold onto old X11Surfaces.)

But we could take inspiration from `wl_surface`'s `Hash`-implementation and hash the pointer of the internal `Arc` for the `SharedSurfaceState`.

**Comment by m4rch3n1ng** [comment]
i just realised, that it also doens't impl `Eq`, and to actually use it in a HashSet it also has to be `Eq`, and if you check for alive-ness in `Eq`, but don't `Hash` it, then it violates the [`Hash` and `Eq` property](https://doc.rust-lang.org/std/hash/trait.Hash.html#hash-and-eq), so it shouldn't be used like this.

i also only now realised, that `ToplevelSurface` also is neither `Hash` nor `Eq`, so i can't use a `HashSet` anyway
