### ISSUE TITLE
use RPC to make smithay language agonistic

### ISSUE THREAD

**Issue by unmellow** [Smithay/smithay#150]
I read [this](https://way-cooler.org/blog/2019/04/29/rewriting-way-cooler-in-c.html) and thought to prevent this from happening in the future RPC 
in the style of what Raph Levien did with [xi-editor](https://github.com/xi-editor) would be the way to go.
 I assume this project is younger and more capable of making this change than wlroots which is why I'm suggesting this to you.

**Comment by unmellow** [comment]
on another note one reason I've heard for why people are switching to Wayland is the fact that there are fewer config files to search for around the system i don't think using RPC would necessitate having a separate config for smithay an example of how to avoid this is to have the compositor send init calls that tell you what settings to run with another idea that might work that I'ld like to put out into the world is to have smithay be a wasm+wasi binary this seems like a nice alternative option but i think RPC is the better way to go especially with xi-editor as an example

**Comment by unmellow** [comment]
it might be possible to do this with some sort of wrapper library on top of whatever API you end up building too. but I would prefer having the primary way to use this be through RPC.

**Comment by vberger** [comment]
Hi, and thanks for your interest :)

However, I think something like RPC is quite out of scope for Smithay currently, such a thing would be too high level. Smithay is not a compositor, but rather a library toolkit to build them, similarly to wlroots. It's not even a standalone program.

Also, Smithay requires the compositor app to integrate tightly in a few quick paths (for the drawing code for example) and I'm afraid an RPC mechanism may introduce a lot of latency.

Making some programmable compositor that can be controlled by RPC could typically rather be a project built on top of Smithay. I think that would be quite an interesting project, but there is no reason to have this functionality inside Smithay directly.
