### ISSUE TITLE
Mouse in anvil is limit to 1920x1080 square at the top left on 4k screen

### ISSUE THREAD

**Issue by kchibisov** [Smithay/smithay#151]
When starting anvil from a tty with `cargo run --features logind -- --tty-udev` the mouse is limited to 1080p area in top left corner.

**Comment by vberger** [comment]
I suspect this is strongly correlated with the fact that anvil hardcodes the size of its output to be 1920x1080 there:

https://github.com/Smithay/smithay/blob/0140de89fb9fd0cc671ba045bc1bc86e68a48fac/anvil/src/udev.rs#L198
