### ISSUE TITLE
Sixel Image Previews via Chafa Are Broken

### ISSUE THREAD

**Issue by masroof-maindak** [Smithay/smithay#1557]
On River, terminal image previews function as expected with no misbehaviour. On Niri however, they randomly flicker or simply do not update to the latest image. This effect is more pronounced when I move between windows. The creator of Niri believes it to be a Smithay issue since the effect is observed in Cosmic too -- although I can't screen-record there because it doesn't support `wlr-screencopy-unstable-v1`.

https://github.com/user-attachments/assets/e4e4b380-0588-4e59-9580-73b9976540ba
**Niri**

https://github.com/user-attachments/assets/5b952012-d753-46d5-a0c6-159f7b318d50
**River**

**Comment by cmeissl** [comment]
Can you please provide reproduction steps? Ideally for anvil, but I can also try with niri.

**Comment by masroof-maindak** [comment]
> Can you please provide reproduction steps? Ideally for anvil, but I can also try with niri.

- `niri`, `cosmic-group`, `river`, and `foot`, and `chafa` (this is the package that actually draws the images) are from the official Arch repo
- Showcased in the videos above are [spotify-player](https://github.com/aome510/spotify-player) (needs to be built with the 'image' feature), and [lf](https://github.com/gokcehan/lf) (using [this](https://github.com/fiplox/ctpv) fork of the `ctpv` previewer). 

### lf

```bash
# install lf, chafa & foot

# build lf previewer
git clone https://github.com/fiplox/ctpv.git
cd ctpv/
git checkout chafa-fix 
make
sudo make install
```

Then, add the following lines to `~/.config/lf/lfrc`:
```
set previewer ctpv
set cleaner ctpvclear
&ctpv -s $id
&ctpvquit $id
```

### Spotify-player

I'd advise staying away from testing using spotify_player for now since Spotify tweaked the way third party clients authenticate and the process involves jumping through a couple of hoops at the moment.

If you still want to however, you will need to first clone [librespot-auth](https://github.com/dspearson/librespot-auth), run it with `cargo run -- --class=computer --name "<whatever_you_want>"`, approve it from any other Spotify client, and place the produced `credentials.json` file in `~/.cache/spotify-player`.

Then you can input your credentials into the Spotify client by running `spotify_player authenticate`, else it will fail during authentication. Note that this client also requires a premium account.

---

Please let me know if there's any other information that would help.

**Comment by cmeissl** [comment]
Thanks for the instruction, I was able to install and configure lf with ctpv under fedora. Unfortunately I don't seem to be able to reproduce the issue under niri. Can you please share the versions you used during testing?

**Comment by masroof-maindak** [comment]
**niri** - 0.1.9
**ctpv** - 1.1 (fiplox' fork)
**lf** - tested using both git and 32.1
**foot** - 1.18.1 +pgo +ime +graphemes -assertions
**chafa** - 1.14.2

**Comment by masroof-maindak** [comment]
Tested with some other terminals.

Wezterm works, but it doesn't use the sixel graphics protocol, it uses Iterm2's I believe.

Konsole is also bugged.

![image](https://github.com/user-attachments/assets/d40940e7-c1c7-4187-a5d9-758add872718)
*the bugged image preview behind the PWD's contents is from `blockchain-asg2.pdf`*.

**Comment by cmeissl** [comment]
Thanks, tried again with `lf` and it seems to work fine on my system. Not sure where the artifacts come from.
Can you run the clients one by one with `WAYLAND_DEBUG=1`, reproduce the issue and upload the log here?

@YaLTeR Are you able to reproduce this issues?

**Comment by YaLTeR** [comment]
I installed lf r32 from https://copr.fedorainfracloud.org/coprs/pennbauman/ports/ and built ctpv, but I can't get the sixel preview to show up. This is all I get:

![image](https://github.com/user-attachments/assets/ddecff58-5a0d-4f0c-ab91-8b8ddaf44efc)

By itself, chafa and ctpv do produce sixel images in foot. There seems to be a damage issue in foot itself with scrolling sixel images, but it doesn't flicker or do anything weird in niri for me. Wezterm shows sixels fine with `chafa -f sixel` and doesn't flicker.

**Comment by masroof-maindak** [comment]
> I installed lf r32 from https://copr.fedorainfracloud.org/coprs/pennbauman/ports/ and built ctpv, but I can't get the sixel preview to show up. This is all I get:
> 
> ![image](https://private-user-images.githubusercontent.com/1794388/373757340-ddecff58-5a0d-4f0c-ab91-8b8ddaf44efc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjkyNTcsIm5iZiI6MTcyODA2ODk1NywicGF0aCI6Ii8xNzk0Mzg4LzM3Mzc1NzM0MC1kZGVjZmY1OC01YTBkLTRmMGMtYWI5MS04YjhkZGFmNDRlZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMTkwOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxNDYwNzE1YTUyODBmZDM4ZWMzZjcyZjBlMjFhNmNiZDg3MjJlZDE2NjkxMDI0NzNjZGZkNTEwYTc3NTNhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.N4gAEaFQmI-2sl_eEoGVBX_4vtV66z5dkSDcrQ_r7W4)
> 
> By itself, chafa and ctpv do produce sixel images in foot. There seems to be a damage issue in foot itself with scrolling sixel images, but it doesn't flicker or do anything weird in niri for me. Wezterm shows sixels fine with `chafa -f sixel` and doesn't flicker.

Did you make sure to change the branch to `chafa-fix` from the forked repo? The reason that's needed is because Chafa requires the use of a 'polite' flag as of some time ago, that the default ctpv does not set, whilst the linked fork does.

**Comment by masroof-maindak** [comment]
> Thanks, tried again with `lf` and it seems to work fine on my system. Not sure where the artifacts come from. Can you run the clients one by one with `WAYLAND_DEBUG=1`, reproduce the issue and upload the log here?
> 
> @YaLTeR Are you able to reproduce this issues?

I'm supposed to run `WAYLAND_DEBUG=1 lf` and `WAYLAND_DEBUG=1 spotify_player`, right? No output on my terminal if that's the case.

**Comment by PolyMeilex** [comment]
> I'm supposed to run `WAYLAND_DEBUG=1 lf` and `WAYLAND_DEBUG=1 spotify_player`, right? No output on my terminal if that's the case.

I would say to run the terminal itself with Wayland debug env

**Comment by masroof-maindak** [comment]
> > I'm supposed to run `WAYLAND_DEBUG=1 lf` and `WAYLAND_DEBUG=1 spotify_player`, right? No output on my terminal if that's the case.
> 
> I would say to run the terminal itself with Wayland debug env

Thank you.

[log.txt](https://github.com/user-attachments/files/17264240/log.txt)

Here's the log @cmeissl. Generated with `WAYLAND_DEBUG=1 foot -D ~/Screenshots > log.txt 2>&1`.

**Comment by dnkl** [comment]
Pretty sure this is an issue in foot, related to the double buffering smithay compositors forces foot to do.

**Comment by dnkl** [comment]
Upstream bug report: https://codeberg.org/dnkl/foot/issues/1851
Upstream PR: https://codeberg.org/dnkl/foot/pulls/1852

I would appreciate if someone here could test it. I was able to reproduce the issue on a non-smithay compositor by instrumenting the code; it would be great is someone could verify it _actually_ works :)

**Comment by dnkl** [comment]
Disclaimer: since apparently konsole is affected to, there _may_ be a smithay issue as well. But there definitely was a bug in foot (too).

**Comment by YaLTeR** [comment]
Thanks for looking into it

**Comment by masroof-maindak** [comment]
@dnkl compiled from source and it works like a charm, thanks a ton!
