### ISSUE TITLE
Regression in dynamic buffer scale changes

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/smithay#1559]
Introduction of 9a7afcf7b107992182d4998d198412c68b49bf3c has broken the ability to manually set the preferred buffer scale for my surfaces. If I change a surface from scale 2 to 1, then back to 2, it will stay at 1 forever.

**Comment by chrisduerr** [comment]
@Drakulix I'd appreciate some feedback on whether this is intentional or if it's an unintended regression. No point looking into a fix if it doesn't want to be fixed.

**Comment by Drakulix** [comment]
Yes I do consider this a regression. Said commit introduces another layer of scaling, but doesn't replace what was already there. The preferred buffer scale should still work the same, I am personally a bit baffled how exactly this broke, just looking at the code.

**Comment by YaLTeR** [comment]
9a7afcf7b107992182d4998d198412c68b49bf3c also breaks wl_output scale updates to clients. You can test in anvil by running
```
env WAYLAND_DEBUG=1 gtk4-demo 2>| grep -E 'wl_output.*scale'
```
then pressing Super+Shift+P to "scale up". The window should get `wl_output.scale(2)` but starting from that commit it keeps getting `wl_output.scale(1)`.

**Comment by chrisduerr** [comment]
I've tested it just to confirm and #1565 definitely did fix this issue.
