### ISSUE TITLE
Xwayland: investigate fork usage

### ISSUE THREAD

**Issue by YaLTeR** [Smithay/smithay#160]
Forks are used to spawn Xwayland. However, since the application might have created threads prior to spawning Xwayland, fork children must be restricted to async-signal-safe functions, and things like `error!` and `CString::new` don't seem particularly async-signal-safe.

This is probably low-priority but I think it's a good idea nonetheless.

**Comment by psychon** [comment]
Oh, hey, I think I discovered this issue on my own (the forked child segfaulted in `exit()`, which is not among the asyng-signal-safe functions) and thus I wrote #250 to fix this. The fix "dumps" the problem on the library user by providing an API to `fork()` a child process before starting any threads.

I think this issue can be closed.
