### ISSUE TITLE
Cross-compiling smithay/anvil for aarch64.

### ISSUE THREAD

**Issue by rvlander** [Smithay/smithay#173]
I open this issue to track issues I am facing on this journey.

# Issues
## Regenerating bindings for `drm-rs` and `gbm-rs`
It is needed because they are only included for x86_64 in respective crates.
### Step 1 
Try to regenerate bindings for x86_64.
Both `drm-rs` and `gbm-rs`uses deprecated versions of bindgen.
   * I tried updated it and generate bindings with the latest version however:
       * gbm-rs won't compile anymore
       * smithay's drm backend won't compile anymore with updated drm bindings
   * I generated these bindings on a up-to-date version of archlinux x86_64

## Misc
* drm-rs does not compile with stable channel (it uses `#![features]` directives)
   * various of the used features have been integrated in `stable` since.

**Comment by Drakulix** [comment]
Yeah... drm-rs is not entirely smithay's fault, as most work on it is done or at leasted approved by @Slabity (ping, so you are aware of the situation). But I am sure, we could provide a better integration of the bindgen-feature.

gbm-rs is entirely my fault, I have no updated it in ages. I will try to fix it soon.

**Comment by scrblue** [comment]
I put in a pull request for drm-rs which added pregenerated bindings for aarch64; I also made sure all the tests worked on x86_64 and aarch64. I'm taking a look a gbm.rs now. I didn't try cross-compiling though, just building it on an ARM device.

**Comment by scrblue** [comment]
I've gotten Anvil working fine, albeit slowly, on a PinePhone running PostmarketOS after minimal changes to drm-rs and gbm.rs. The only change I made to Smithay or Anvil was changing the default features to make it easier to run quickly during testing. I'll share my changes after I clean it up later, but I don't want to put too much effort into integrating it nicely until I know just how much is going to be rewritten anyway.

**Comment by cmeissl** [comment]
I sucessfully cross compiled for aarch64 and was able to run anvil on a aarch64 device with current master.

**Comment by vberger** [comment]
Well, I guess this works now then.
