### ISSUE TITLE
Anvil fails to compile on recent upgrade of nix to 0.18. 

### ISSUE THREAD

**Issue by minioin** [Smithay/smithay#231]
Compiles fine when downgraded to 0.17.

**Comment by vberger** [comment]
Anvil compiles fine for me. Are you maybe missing a `cargo update` ? The nix update is linked to a git dependency.

**Comment by minioin** [comment]
``cargo update`` fixed it. Thanks.

On a related note, what is the behavior of Super-Enter? I opened anvil on a different tty and it spawned the terminal on my main tty environment.

**Comment by vberger** [comment]
> On a related note, what is the behavior of Super-Enter? I opened anvil on a different tty and it spawned the terminal on my main tty environment.

That's not normal, it should open in anvil. That sounds like a misbehavior of the `WAYLAND_DISPLAY` env variable. Though anvil should set it appropriately.

**Comment by minioin** [comment]
I tried again with different terminals. For gnome-terminal, it opened in my main environment. With ``alacritty``, it opened in correct env. However, when I opened Firefox from ``alacritty``, it first complained that no ``DISPLAY`` variable was set and when I set it to 0 and 1, it opened in my main env both of the times. What is the correct way of initializing environment for anvil? Also, I might poke around with ``anvil`` for a couple of days. Where can I chat with you, in case I need to?

**Comment by vberger** [comment]
For chatting, we have a matrix chatroom at `#smithay:matrix.org`, which is also bridged to `#matrix` on freenode IRC and to gitter on https://gitter.im/smithay/Lobby, so you can join using your preferred method.

I suspect you're observing the lack of XWayland support in anvil. It is currently unimplemented, so X11 apps start on your main environment (the `DISPLAY` environment variable is X11-specific). You can try setting `MOZ_ENABLE_WAYLAND=1` to get firefox to start in Wayland mode. I'm note sure about gnome-terminal though, I'd expect it to be wayland native.

**Comment by minioin** [comment]
``MOZ_ENABLE_WAYLAND=1`` didn't fix it. And I guess, Firefox on Fedora(my current environment) is wayland by default but I can't confirm on this now.

**Comment by kchibisov** [comment]
it's because gtk applications will spawn on a session their original was started, nothing anvil and any other compsitor can do about. that's even true if you start Wayland compositor and x11 wm, it'll spawn where the first window was opened.

**Comment by minioin** [comment]
I checked this now with firefox and it did launch inside given session. Thanks @kchibisov .

Now I would like to know what it is missing(aside from tap to click as default) that I can help myself move it towards a good daily driver. I actually have a couple of days and maybe can contribute some, or at least learn about it. I have heard good things about wlroots and smithay.
