### ISSUE TITLE
Questions regarding this project?

### ISSUE THREAD

**Issue by Joe23232** [Smithay/smithay#239]
I have a few questions regarding this project.

1. Does it have window decoration support? For example
![Full window (options)](https://user-images.githubusercontent.com/34926497/99211116-b7559780-281b-11eb-9c47-9b59782df827.png)

If not then does it plan to implement it?

2. Does it come with its own taskbar and gadgets?
3. Am I able to use this to create my own lockscreen as well?
4. Is it like `dwm` where I add code in a high level manner and then I recompile the entire project?
5. If 4 is true, then whatever file I code in it, is there minimal amount of code and is it straight forward unlike `awesome` WM?

**Comment by vberger** [comment]
Hi, and thanks for you interest!

There seem to be a little confusion about what Smithay is though, so let me clarify. Smithay is a library/framework for developing Wayland compositors, not a Wayland compositor in of itself.

Most of your questions would apply to a compositor project, not Smithay directly, which places itself at a lower-level. Still it would definitely be possible to create a programmable Wayland environment similar to AwesomeWM using Smithay, with custom decorations, taskbars, widgets and lockscreen.

**Comment by Joe23232** [comment]
Oh sorry thanks for clarifying with me.

Do you know other projects that uses Smithay by any chance? Fireplace seems to be dead?

**Comment by vberger** [comment]
I don't think Fireplace is dead, rather @Drakulix has put it on hold while he works with me on Smithay, with the goal of continuing it when Smithay is mature enough for his needs. I guess this would roughly coincide with [our 0.3 milestone](https://github.com/Smithay/smithay/milestone/3).

Other than that, I'm not sure there is an other project for a desktop environment based on Smithay yet. We have an example compositor, [anvil](https://github.com/Smithay/smithay/tree/master/anvil), but it is mostly meant to showcase how Smithay can be used, and is very minimalist.

**Comment by PolyMeilex** [comment]
I'm sorry to hijack a thread, but I'm quite curious about it.
`I guess this would roughly coincide with our 0.3 milestone.`
@Drakulix Do you agree with this statement?

(I ask because if you would consider it mature enough for Fireplace, I would also consider it mature enough for my simple experiments, and subsequently It would make me really excited about 0.3)

**Comment by Drakulix** [comment]
> @Drakulix Do you agree with this statement?

Difficult question...

*Mature enough to start working on fireplace again?*
For sure. A lot of stuff is in place, especially on the backend side. I still have some api-breaking changes in mind for later, but I think it is very much worth testing the current api before doing any more large changes.
Working on another compositor then our toy 'anvil' will also likely help developing smithay in the long run, as anvil is not really meant for every day use.
So yes, I do consider smithay mature enough for working on some more realistic projects and therefor any *experiments*.

(That said I have one more mid-sized api improvement specifically for the drm-backend in mind, that I am currently working one.
I am not sure, if that will make it into 0.3 as I personally would like to get 0.3 done this year. But it is not far off.)

*Mature enough to be able to "finish" fireplace with it?*
Far from it. We are still missing some pretty basic things:
- proper XWayland support
- something like layer-shell to support bars/trays/docks/backgrounds/etc
- damage-tracking to lower battery usage
- and a lot of small things...

As a result I do not consider smithay ready to write a full-blown desktop environment *yet*.

**Comment by PolyMeilex** [comment]
Thank you for your comprehensive answer.
This answers my question completely.

I'm aware of limitations like lack XWayland and damage-tracking, I believe it is not a problem for non-production ready prototypes.

**Comment by Joe23232** [comment]
I see, thanks guys :)

**Comment by vberger** [comment]
BTW, I'll add that if you wish to help us evolve Smithay, we'd gladly mentor you to its internal. 😉

@Drakulix and I are working on it as a hobby mostly, and I also dedicate a lot of my FOSS time to wayland-rs and SCTK, so right now there is a limit to how quickly thing can evolve.

**Comment by Joe23232** [comment]
@vberger 

> BTW, I'll add that if you wish to help us evolve Smithay, we'd gladly mentor you to its internal. wink


Can you please help me, I am a noob to Rust and any programming language really, I have a lack of experience with just how this stuff works? :)

**Comment by vberger** [comment]
@Joe23232 If you are interested, you can maybe join us in the Smithay chatroom so that we can maybe discuss it in amore direct way? We're on Matrix on `#smithay:matrix.org`, but the chatroom is also bridged to `#smithay` on freenode IRC as well as on Gitter at https://gitter.im/smithay/Lobby, depending on which medium you prefer.

**Comment by Joe23232** [comment]
Thanks mate :) Do you guys use Riot for the matrix thing?

**Comment by vberger** [comment]
It's been renamed to Element now, but yes :)

**Comment by Joe23232** [comment]
Oh ok I joined Gitter by the way :)
