### ISSUE TITLE
logind: SwitchToNext/Previous, please add.

### ISSUE THREAD

**Issue by cheako** [Smithay/smithay#256]
Something like: 
https://gitlab.com/cheako/hidcat/-/blob/6eaa386248e74d5d7ea9d9eb26717bd0e0208263/src/main.rs#L79-107

Referance taken from:
https://www.freedesktop.org/wiki/Software/systemd/logind/

**Comment by Drakulix** [comment]
Given we have dropped our logind code in favour of libseat, this is not relevant anymore.
