### ISSUE TITLE
Consider libseat support

### ISSUE THREAD

**Issue by vberger** [Smithay/smithay#262]
wlroots is supporting it, weston is apparently going to as well.

libseat has a [very simple API](https://git.sr.ht/~kennylevinsen/seatd/tree/master/item/include/libseat.h), which should thus be very easy to support.

Furthermore, it appears that wlroots is planning to delegate its (e)logind support to libseat as well, meaning libseat is quite likely to get packaged and distributed in the near future, at which point we might consider doing the same thing.

**Comment by PolyMeilex** [comment]
Not sure if there is any value in sharing it, but I played around a bit with it in my [libseat-rs](https://github.com/PolyMeilex/libseat-rs) repo. 
As far as I remember in wlroots repo there is even an issue opened related to dropping logind code entirely, and depending on libseat instead
