### ISSUE TITLE
XDG PositionerState is not updated properly

### ISSUE THREAD

**Issue by PolyMeilex** [Smithay/smithay#359]
It took me an hour to figure out why my popups always report None or default values for their positioners. It turns out that [positioner state of XdgPopupSurfaceRoleAttributes](https://github.com/Smithay/smithay/blob/dbd03567ff18e62236a6c288008f15f2c39cbff6/src/wayland/shell/xdg/mod.rs#L323) is never updated.
In fact, `XdgPopupSurfaceRoleAttributes::positioner` is actually never used in the codebase anywhere.

 `xdg_positioner::XdgPositioner` has a `PositionerState` inside of its user data, but it is not exposed to the user:
https://github.com/Smithay/smithay/blob/dbd03567ff18e62236a6c288008f15f2c39cbff6/src/wayland/shell/xdg/xdg_handlers.rs#L164-L167

**Comment by cmeissl** [comment]
Oh, i forgot to set the positioner state in the popup, sorry 😩

For updating the geometry after the initial geometry has been sent (initial configure) we need to add support for reactive popups from the protocol. The default/inital geometry can of course be overridden without this.

**Comment by PolyMeilex** [comment]
I just simply want to flip popup when it gets outside of output, so I just need some way to receive initial gravity. I don't think I need reactive popup for that.

**Comment by cmeissl** [comment]
If the geometry of the popup does not change probably not. Not sure if flipping can be achieved without changing the geometry. If i read the spec correctly the geometry is only allowed to change when the positioner is reactive.

**Comment by cmeissl** [comment]
I opened a pr for v3 support where the inital positioner state has been added to the newpopup event, should make initial placement easier.
