### ISSUE TITLE
Restore TTY state on exit/panic

### ISSUE THREAD

**Issue by vberger** [Smithay/smithay#37]
While trying to run the DRM example, the first time I had forgotten to set the `XDG_RUNTIME_DIR` env variable. As a result, the example panicked.

Rather than dropping me back to the shell in my TTY (like what X11 does when it fails to start for example), the screen remained black until I TTY-switched to an other and back.

I don't know at all what is required for this to work, I'll probably only be possible to handle properly once we have the TTY-switching logic.

**Comment by Drakulix** [comment]
Done with #56
