### ISSUE TITLE
Destroy `UserDataMap` entries on object destruction

### ISSUE THREAD

**Issue by DemiMarie** [Smithay/smithay#379]
Right now, entries in a `UserDataMap` are only destroyed when the object (such as a `WlSurface`) is destroyed.  This is counterintuitive and makes memory leaks due to circular references very easy to create.

A more developer-friendly approach would be to destroy the `UserDataMap` when the protocol-level object has been destroyed, whether or not there are other Rust-level references to the object.  This would trigger the destructors of the objects in the map, allowing circular references to be broken much more easily.

**Comment by i509VCB** [comment]
I think this issue should be moved to wayland-rs
