### ISSUE TITLE
Implement fallback renderer (pixman or siimiliar)

### ISSUE THREAD

**Issue by HeavyRain266** [Smithay/smithay#399]
Hello, I know that this will require a lot of work but this would be good practice to still run compositor through fallback renderer when gles2 fails e.g. on older hardware. Compositor would be rendered by software rendering like pixman (this is what wlroots did) and optional ENV variable like `SMITHAY_RENDERER=fallback ./anvil`.

**Comment by vberger** [comment]
I think this is a duplicate of #330 :)

**Comment by HeavyRain266** [comment]
Oh, I'm blind and after looking into all issues didn't saw this one...
