### ISSUE TITLE
0.30 - Seat implementation is not correct

### ISSUE THREAD

**Issue by PolyMeilex** [Smithay/smithay#461]
This is note to future self:
I believe that seat impl that I did for 0.30 port is not entirely right, as it takes away the ability to create multiple seats, although this is nish case, it is really easy to add/fix so it's better to do so.

This would most likely be done by splitting SeatState into two structs, one would live in WlSeat global data and second one would be as is now, this way each global would have it's own separate state.

**Comment by i509VCB** [comment]
Github didn't close this issue.
