### ISSUE TITLE
Please commit Cargo.lock files

### ISSUE THREAD

**Issue by colemickens** [Smithay/smithay#496]
For repos that provide both lib+bin, it is appropriate to still commit lock files. It is not impactful if Smithay is being used as a lib.

Without this, I cannot package Smithay with Nix / for nixpkgs.

**Comment by vberger** [comment]
FYI, only Smithay the library is meant to be versioned and released, anvil is not meant to be, it really is more of a testbed for anvil than anything else.

**Comment by colemickens** [comment]
Ack. In the past for things like wlroots we will package examples/test apps into a separate derivation output. This makes the derivation useful for developers as well who utilize nix in the development workflow.

That having been said, Smithay wouldn't be used the same way that wlroots is used in nixpkgs, since, as you point out, Smithay would normally be imported into some other application with Rust which itself would be packaged (most Rust libs aren't individually packaged).

I still don't think there's harm in committing the Cargo.lock, but I understand either way if you do/don't. I'll probably just hang onto my (local, not planned for upstreaming now anyway) package derivation and see what happens. (I am sort of eager to just tinker with anvil and I'm a stubborn nix-er and just packaging it was the easiest way to tinker...)
