### ISSUE TITLE
Allow compositor set_role if role is the same as current one

### ISSUE THREAD

**Issue by PolyMeilex** [Smithay/smithay#579]
https://github.com/Smithay/smithay/blob/6d6e980cefd0486fa9b780325cbb698891414d4f/src/wayland/compositor/tree.rs#L167-L169

I believe that this check should take into account current role, and if it is the same, just allow it.
Weston and wlroots do that.

Perhaps we should clarify this upstream.

**Comment by vberger** [comment]
Indeed, this is an error on our side, [the `wl_surface` spec](https://wayland.app/protocols/wayland#wl_surface) is pretty clear:

> A surface can have only one role at a time. Initially a wl_surface does not have a role. Once a wl_surface is given a role, it is set permanently for the whole lifetime of the wl_surface object. Giving the current role again is allowed, unless explicitly forbidden by the relevant interface specification.

**Comment by PolyMeilex** [comment]
Indeed, If that's the case I'll prepare a PR
