### ISSUE TITLE
Design of InputBackend trait

### ISSUE THREAD

**Issue by vberger** [Smithay/smithay#6]
Here is to discuss the API we'll use for the `InputBackend` trait, to abstract over possible input sources.

Comes to mind:

- glutin
- raw X11
- wayland (running compositor as a client)
- libinput

My first take would be first study libinput API, which is most likely the most general of these 4 possibilities, and use this insight to build the trait.

This is not an hard requirement, after all we're not going to set the API in stone (at least not before 1.0), and we can also take a more incremental approach.

Basically, I think we can go the `Handler` way, as for the wayland-api part, and require some handler struct implementing a trait that'd look like:

```rust
trait InputBackendHandler {
    fn on_kbd_event(&mut self, ...);
    fn on_mouse_move(&mut self, ...);
    fn on_mouse_button(&mut self, ...);
   .... // touch events ? Other things ?
}
```

from this remains the question of multiple keyboard/mouses? I believe libinput already has the same notion of "seat" that the wayland protocol has. We should probably expose it?

**Comment by Drakulix** [comment]
Multiple keyboard are actually a great problem in `wlc` because you cannot have any keyboard specific options like the layout.

Maybe the handler could be structured like this?

```rust
#[derive(Hash, PartialEq, Eq)]
pub enum InputDevice
{
    Keyboard(KeyboardDevice),
    Mouse(MouseDevice),
    // touch screen ? gamepad ?
}

trait InputBackendHandler {
    fn on_input_attached(&mut self, device: &mut InputDevice);
    fn on_input_detached(&mut self, device: &mut InputDevice);
    fn on_kbd_event(&mut self, device: &mut KeyboardDevice, ...);
    fn on_mouse_move(&mut self, device: &mut MouseDevice, ...);
    fn on_mouse_button(&mut self, device: &mut MouseDevice, ...);
   .... // touch events ? Other things ?
}
```

Glutin could just always initialize "one" mouse & keyboard.

**Comment by Drakulix** [comment]
Also you will maybe also want mouse specific options. Especially trackpads should be configurable.
E.g. https://github.com/SirCmpwn/sway/wiki#configure-touchpad-and-other-input-devices

**Comment by vberger** [comment]
For reference: the overview structure of libinput : https://wayland.freedesktop.org/libinput/doc/latest/seats.html

**Comment by vberger** [comment]
Looks like we settled on something. :)
