### ISSUE TITLE
desktop: subsurface destruction artifacts

### ISSUE THREAD

**Issue by cmeissl** [Smithay/smithay#641]
When a sub-surface is destroyed the old geometry is not damaged.
This results in artificats where parts of the gone sub-subsurface are still visible on-screen.

**Comment by Drakulix** [comment]
yeah true. but the basic idea should work for the most part, I hope. Because the destruction_callback is not giving us much more options than using something like a channel or just store the geometry inside the `SurfaceData`.

**Comment by cmeissl** [comment]
Not sure if this works for all subsurfaces. There could be a sub-subsurface where the parent subsurface gets unmapped. This should also use the geometry of the sub-subsurface as damage. So we should also damage on unmap and use the complete (previous?) surface tree geometry for the damage.

**Comment by Drakulix** [comment]
> Not sure if this works for all subsurfaces. There could be a sub-subsurface where the parent subsurface gets unmapped. This should also use the geometry of the sub-subsurface as damage. So we should also damage on unmap and use the complete (previous?) surface tree geometry for the damage.

Well in that case we probably need a dirty_flag for the `Window` (maybe an AtomicBool) and diff the surface_tree on the next accumulated_damage call, if that is true, or something like that.
