### ISSUE TITLE
SeatHandler is not needed

### ISSUE THREAD

**Issue by i509VCB** [Smithay/smithay#706]
SeatHandler's &SeatState is unused and therefore useless.

**Comment by Drakulix** [comment]
Not really any more the case after https://github.com/Smithay/smithay/pulls?q=is%3Apr+is%3Aclosed+input, no?

**Comment by PolyMeilex** [comment]
Initially it was done to allow adding `SeatState::seats()` in the future, and the possibility to and some helpers like, last active seat, or whatever may be useful, So the need for `Vec<Seat>` in user's code would be mitigated.

My idea was for it to work like so:
```rs
seat_state.add_seat(...); // Init new Seat global

seat_state.seats(); // Newly added seat is listed here

seat_state.remove_seat(...) // Disable/Remove Seat Global and remove it from the list
```

And coincidently Drakulix's changes align with that, as now seat_state is responsible for seat creation.
