### ISSUE TITLE
Investigate removing inner data of DmabufState

### ISSUE THREAD

**Issue by i509VCB** [Smithay/smithay#707]
Now that `DisplayHandle` is clone, we could have DmabufGlobal manage destroying itself, thereby turning DmabufState into a marker type.

**Comment by Drakulix** [comment]
Now that the default feedback is a thing, the `DmabufState` needs to be able to reference alive `DmabufGlobal`s. Using weak references to make the globals cleanup after themselves only makes the code unnecessarily more complicated.
