### ISSUE TITLE
Cleanup surface state, if role-objects are destroyed

### ISSUE THREAD

**Issue by Drakulix** [Smithay/smithay#768]
While the role of a surface is fixed during it's lifetime, surfaces may be re-used as long as the role never changes.
This means we need to cleanup state associated with said role on destruction of their respective role-objects (e.g. XdgToplevelSurfaceRoleAttributes on destruction of the xdg_toplevel object).

**Comment by PolyMeilex** [comment]
Sounds similar to #580
