### ISSUE TITLE
compositor: erroneous wl_subcompositor.get_subsurface calls are handled incorrectly

### ISSUE THREAD

**Issue by vyivel** [Smithay/smithay#774]
Consider this Wayland client: https://paste.sr.ht/~vyivel/8c88da9bf8203a3c68701ee4af51c28158ff9c70

It has 3 modes:

- `self`: the subsurface's parent is set to the subsurface itself.
  Expected behavior: the client is closed with `wl_subcompositor.bad_surface`.
  Actual behavior: `anvil` freezes (on a mutex?).
- `loop`: subsurfaces form a loop.
  Expected behavior: the client is closed with `wl_subcompositor.bad_surface`.
  Actual behavior: the client is closed with a correct error, but the message "Surface already has a role." doesn't seem right.
- `reuse`: the `wl_subcompositor.get_subsurface` is called with identical values twice.
  Expected behavior: the client is closed with `wl_subcompositor.bad_surface`.
  Actual behavior: `anvil` panics (`thread 'main' panicked at 'assertion failed: child_guard.parent.is_none()', src/wayland/compositor/tree.rs:303:13`).

**Comment by i509VCB** [comment]
Does wlcs have tests for these that we haven't enabled? Or do we want to make an issue for those there.

**Comment by vyivel** [comment]
> Does wlcs have tests for these that we haven't enabled?

Doesn't seem so.
https://github.com/MirServer/wlcs/blob/main/tests/subsurfaces.cpp#L935

**Comment by Drakulix** [comment]
Hmm, fixing those is one thing (which we should do), but without proper testing, I fear these could easily slip back into the code base. We should try and contribute tests to wlcs for this one.
