### ISSUE TITLE
How can I set atoms on WindowInner from the Anvil?

### ISSUE THREAD

**Issue by jaunkst** [Smithay/smithay#813]
Where is the best place to set atoms on WindowInner from Anvil  ?

**Comment by i509VCB** [comment]
I haven't really considered setting atoms on windows in the x11 backend and general extensibility. Would be interested though to see if you have anything on that.

I believe the window id can be obtained somewhere.

**Comment by jaunkst** [comment]
I added it to InnerWindow directly to get a few atoms working to setup a WM in a gamescope overlay. I would like to be able to do proper atom decorations. It had me going for awhile trying to figure out what was going on. I managed to figure it out after observing the window with xprop. That's when I realized the window id I was using was wrong.

**Comment by jaunkst** [comment]
I just reused the atom_manager for the new keys, and used this to set it up.  I know we should have a better approach. I wasn't sure if there was one already. 
`

            connection
                .change_property32(
                    PropMode::REPLACE,
                    self.id,
                    self.atoms.STEAM_OVERLAY,
                    AtomEnum::CARDINAL,
                    &[1],
                )
                .ok();

            connection
                .change_property32(
                    PropMode::REPLACE,
                    self.id,
                    self.atoms.STEAM_INPUT_FOCUS,
                    AtomEnum::CARDINAL,
                    &[1],
                )
                .ok();

`

**Comment by jaunkst** [comment]
Gamescope wants X11 windows to allow for external overlays to be wired up through atoms. By using this great library I can focus on wayland protocol to enable my UX. I'll look around and see if there is a good way to approach this. Getting the InnerWindow id would be a great step for now.

**Comment by i509VCB** [comment]
Wouldn't this work as the id? https://smithay.github.io/smithay/smithay/backend/x11/struct.Window.html#method.id

**Comment by jaunkst** [comment]
is screen.root the same id in the anvil/wayland/mod.rs ?

**Comment by i509VCB** [comment]
Uhh, not sure what you are referencing with the root screen.

**Comment by jaunkst** [comment]
Yeah, No its not it. I don't see how to best get the x11 backend window in anvils side of things.

**Comment by jaunkst** [comment]
I figured it out. Should be able to do what i need in x11.rs where we create the x11 backend window.  There isn't a connection yet, and we need to lookup the atoms.
