### ISSUE TITLE
Rendering functions should document expected `&[RenderElement]` z-order

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/smithay#895]
Current documentation for `DamageTrackedRenderer` states the following:

> Render this output

During rendering I would usually expect back to front element order, however this function expects front to back order.
While users might still run into and notice this issue by doing it wrong the first time, there should be documentation reassuring them what the correct element order is meant to be.

CC @cmeissl

**Comment by cmeissl** [comment]
Before the next release we will probably also rename `DamageTrackedRenderer` to better reflect that it is not a renderer.
Only components actually implementing the `Renderer` trait should have `Renderer` in their name.
Actually I think it would be a good idea to make both changes in a single PR, rename + docs.
