### ISSUE TITLE
Tinting introduced 25% performance penalty

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/smithay#897]
Commit 699b30395875771df81934878b190c1d613e89ff introduced a rendering flag for tinting, which added additional code to the shaders. Having this shader code present, increases the `glFinish` time on the PinePhone Pro from ~4ms to ~5ms with my compositor.

**Comment by cmeissl** [comment]
@chrisduerr this should be fixed by #901, can you please verify?

**Comment by chrisduerr** [comment]
I can confirm that #901 changed the performance for `alacritty -e yes` from ~6ms to ~5ms for me. I can't guarantee that this is because of tinting but I'd assume it's fixed.
