### ISSUE TITLE
Overlaps or touches logic is broken

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/smithay#898]
Currently the intersection method on rectangles uses `overlaps_or_touches(other)` to determine whether the result should be `None` or not. However two touching rectangles do not have an intersection which should return `None` rather than returning an empty rectangle as it does right now.

The result of this is that the `DamageTrackedRenderer`'s damage calculation will incorrectly request windows to draw with zero-sized damage regions.

Incorrect damage calculation location:
https://github.com/Smithay/smithay/blob/7b32864bc1c0e1a35d83b1ebb67544f7bced0210/src/backend/renderer/damage.rs#L402

I would have just nuked the entire `overlaps_or_touches` logic in favor of using `overlaps` everywhere, but I don't really understand why you would use `overlaps_or_touches` here to begin with so I'll leave it to the people that wrote this code to fix it. Based on my testing, just replacing it all with `overlaps` fixed the issue.

**Comment by cmeissl** [comment]
I will take care of that issue

cc @Drakulix

**Comment by cmeissl** [comment]
> Currently the intersection method on rectangles uses `overlaps_or_touches(other)` to determine whether the result should be `None` or not. However two touching rectangles do not have an intersection which should return `None` rather than returning an empty rectangle as it does right now.
> 
> The result of this is that the `DamageTrackedRenderer`'s damage calculation will incorrectly request windows to draw with zero-sized damage regions.
> 
> Incorrect damage calculation location:
> 
> https://github.com/Smithay/smithay/blob/7b32864bc1c0e1a35d83b1ebb67544f7bced0210/src/backend/renderer/damage.rs#L402
> 
> I would have just nuked the entire `overlaps_or_touches` logic in favor of using `overlaps` everywhere, but I don't really understand why you would use `overlaps_or_touches` here to begin with so I'll leave it to the people that wrote this code to fix it. Based on my testing, just replacing it all with `overlaps` fixed the issue.

In most cases `overlaps` should be enough, yes. But for damage we want to also merge rectangles that just touch.
Before I added `overlaps_or_touches` we only had `overlaps` which had the logic from `overlaps_or_touches`, but this broke direct scan-out for some clients (csd touching the main surface). Anyway, the use of this function in `intersection` is wrong and #961 should fix that.
