### ISSUE TITLE
Text input causes communication breakdown

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/smithay#937]
It seems like some combination of input_method/text_input coupled with Squeekboard/Alacritty causes Squeekboard/Alacritty to crash. The following errors are reported:

Squeekboard:

```
Gdk-Message: 11:12:58.528: Error flushing display: Broken pipe
```

Alacritty:

```
Error: "Event loop terminated with code: 1"
```

To my knowledge both of these errors indicate that the communication to the compositor was somehow interrupted.

## Reproduction

I've applied the following patch to automatically focus new windows with Anvil. It might be possible without this patch but from what I could tell Anvil never actually calls `text_input.set_focus`, which is required to reproduce the issue.

```diff
diff --git a/anvil/src/shell/xdg.rs b/anvil/src/shell/xdg.rs
index d755e602b9..98e2691551 100644
--- a/anvil/src/shell/xdg.rs
+++ b/anvil/src/shell/xdg.rs
@@ -45,8 +45,17 @@ impl<BackendData: Backend> XdgShellHandler for AnvilState<BackendData> {
         // Do not send a configure here, the initial configure
         // of a xdg_surface has to be sent during the commit if
         // the surface is not already configured
-        let window = WindowElement::Wayland(Window::new(surface));
+        let window = WindowElement::Wayland(Window::new(surface.clone()));
         place_new_window(&mut self.space, &window, true);
+
+        let serial = smithay::utils::SERIAL_COUNTER.next_serial();
+        let keyboard = self.seat.get_keyboard().unwrap();
+        keyboard.set_focus(self, Some(window.into()), serial);
+
+        use smithay::wayland::text_input::TextInputHandle;
+        if let Some(text_input) = self.seat.user_data().get::<TextInputHandle>() {
+            text_input.set_focus(Some(surface.wl_surface()), || {});
+        }
     }
 
     fn new_popup(&mut self, surface: PopupSurface, positioner: PositionerState) {
```

Once this patch is applied, all that is required is starting Alacritty's master (I don't think this happens without the IME purpose setting patch, or at least not as regularly), then starting Squeekboard. Most of the time this causes either one application or the other to crash with the previously mentioned error.

Looking very loosely at the server/client logs, it seems like the issue happens somewhere around `zwp_text_input_v3::commit`, though I wouldn't take my word for that as gospel.

**Comment by chrisduerr** [comment]
Pinging @rano-oss since he wrote the code and maybe has some idea about it.

**Comment by rano-oss** [comment]
text input focus follows keyboard focus, ref: https://github.com/Smithay/smithay/blob/master/src/wayland/input_method/input_method_keyboard_grab.rs#L81.

Just setting the keyboard focus should be enough. It might be that setting the focus twice creates the communication error?

**Comment by chrisduerr** [comment]
> Just setting the keyboard focus should be enough.

It is not. Without `text_input.set_focus` it will not pop up the virtual keyboard (which obviously doesn't cause any crashes).

**Comment by rano-oss** [comment]
hmm, maybe squeekboard does not use the keyboard to set its focus? I will see if I can carve out some time top take a look at this in the week.

**Comment by chrisduerr** [comment]
I cannot reproduce this anymore. My best guess is that the null-truncation patch might have fixed this?
