### ISSUE TITLE
Improve xdg_shell abstraction to better reflect the protocol

### ISSUE THREAD

**Issue by vberger** [Smithay/smithay#97]
The xdg_shell protocol associates a specific meaning to its elaborate configure dance. To honor it, our abstraction should keep track of the contents of the different configure sent to the client, and when the client acks one, discard all the older ones, and mark this one as the "current" state of the client.

As such, smithay's users should not assume that the client automatically is in the state they last configured it to, but rather smithay should expose some API to allow for accessing the last state that was acked by the client.

Also, other protocol extensions tend to piggy-back more state on the xdg_shell configure, so we need to allow associating arbitrary data with a state, possibly with a similar mechanism as what we currently do with the role data, via traits (but as a product type rather than a sum type in this case).

So, a seemingly generic API t expose on Toplevel/Popup surfaces would be something like:

```rust
/// Mutably access the current pending state of this surface, to modify its contents
///
/// This can be used to integrate data from external protocols into the xdg_shell
/// configure mechanism
pub fn with_pending_state<T, F>(&self, F) -> T 
    where F: FnOnce(&mut ConfigureState) -> T
{
    /* ... */
}

/// Send the current pending state to the client
///
/// A copy of the pending state is stored as sent to the client, and will become the
/// current state when the client acks it.
pub fn send_configure(&self) {
    /* ... */
}

/// Retrieve last ackend state of this surface
pub fn with_current_state<T, F>(&self, F) -> T
    where F: FnOnce(&ConfigureState) -> T
{
    /* ... */
}
```

**Comment by YaLTeR** [comment]
But the pending state is applied on commit, and the client acking a configure event doesn't actually tell us anything about it because the configure event does not contain any info that's present in the pending state? So I think it should rather be a "last committed state", similar to what I'm currently adding to `SurfaceData` in anvil.

**Comment by vberger** [comment]
These are two different pending states. The one sent by the server and acked by the client (which is the one this issue is concerned with), and the one sent by the client and commited on surfaces.

So here, the last acked state is the state the server should use as a reference wrt to what it has sent and the client is supposed to follow (for example about the configure size for a maximized surface, for which not obeying is a protocol error).

**Comment by vberger** [comment]
Done in #286, thanks @cmeissl !
